// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { Kind, type GraphQLResolveInfo } from "graphql";
import { DataLoader } from "@corpdk/dal-core";
import type { PubSub } from "../generated-pubsub.js";
import {
  GeneratedPhase5WidgetRepository,
} from "../repositories/index.js";

export interface DalContext {
  actorId: string | null;
  pubsub: PubSub;
  repositories: {
    phase5Widget: GeneratedPhase5WidgetRepository;
  };
  loaders: Record<string, DataLoader<string, unknown> | DataLoader<string, unknown[]>>;
}

export interface CreateDalContextOptions {
  /** Actor ID from auth context; null uses repository "system" fallback. */
  actorId?: string | null;
}

export function createDalContext(pubsub: PubSub, options?: CreateDalContextOptions): DalContext {
  const repositories = {
    phase5Widget: new GeneratedPhase5WidgetRepository(),
  };
  const ctxRef = {
    actorId: options?.actorId ?? null,
    pubsub,
    repositories,
    loaders: {} as DalContext["loaders"],
  } as DalContext;



  return ctxRef;
}

export const generatedResolvers = {
  DateTime: {
    serialize: (v: unknown) => (v instanceof Date ? v.toISOString() : v),
    parseValue: (v: unknown) => {
      if (typeof v !== "string") throw new TypeError("DateTime must be a string");
      return v;
    },
    parseLiteral: (ast: { kind: string; value?: string }) => {
      if (ast.kind !== Kind.STRING) throw new TypeError("DateTime must be a string");
      return ast.value ?? "";
    },
  },
  Query: {
    hello: (_: unknown, args: { name?: string | null }): string =>
      `Hello, ${args.name ?? "world"}!`,

    status: (): { ok: boolean; timestamp: string } => ({
      ok: true,
      timestamp: new Date().toISOString(),
    }),

    phase5Widgets: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.phase5Widget.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    phase5Widget: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.phase5Widget.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    phase5WidgetConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.phase5Widget.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    phase5WidgetsCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.phase5Widget.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    phase5WidgetAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.phase5Widget.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),
  },
  Mutation: {
    ping: (
      _: unknown,
      args: { message: string },
      ctx: DalContext,
    ): { message: string; timestamp: string } => {
      const result = { message: args.message, timestamp: new Date().toISOString() };
      ctx.pubsub.publish("PING_SENT", { pingSent: result });
      return result;
    },

    createPhase5Widget: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.phase5Widget.create(args.input as never, { actorId: ctx.actorId });
      if (result.phase5Widget && result.userErrors.length === 0) {
        const event = ctx.repositories.phase5Widget.toChangeEvent("CREATED", [result.phase5Widget.id]);
        ctx.pubsub.publish("PHASE5WIDGET_CHANGED", { phase5WidgetChanged: event });
      }
      return result;
    },

    bulkCreatePhase5Widget: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.phase5Widget.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.phase5Widget.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("PHASE5WIDGET_CHANGED", { phase5WidgetChanged: event });
      }
      return result;
    },

    bulkDeletePhase5Widget: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.phase5Widget.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.phase5Widget.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("PHASE5WIDGET_CHANGED", { phase5WidgetChanged: event });
      }
      return result;
    },

    bulkDeletePhase5WidgetByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.phase5Widget.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updatePhase5Widget: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.phase5Widget.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.phase5Widget && result.userErrors.length === 0) {
        const event = ctx.repositories.phase5Widget.toChangeEvent("UPDATED", [result.phase5Widget.id]);
        ctx.pubsub.publish("PHASE5WIDGET_CHANGED", { phase5WidgetChanged: event });
      }
      return result;
    },

    bulkUpdatePhase5Widget: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.phase5Widget.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.phase5Widget.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("PHASE5WIDGET_CHANGED", { phase5WidgetChanged: event });
      }
      return result;
    },

    bulkUpdatePhase5WidgetByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.phase5Widget.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deletePhase5Widget: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.phase5Widget.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.phase5Widget.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("PHASE5WIDGET_CHANGED", { phase5WidgetChanged: event });
      }
      return result;
    },
  },
  Subscription: {
    pingSent: {
      subscribe: (_: unknown, _args: unknown, ctx: DalContext) =>
        ctx.pubsub.subscribe("PING_SENT"),
    },

    phase5WidgetChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("PHASE5WIDGET_CHANGED")) {
          const event = payload.phase5WidgetChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },
  },


};
