// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { createAppPubSub } from "@corpdk/pub-sub";
import type { EntityChangeEventPayload } from "@corpdk/dal-core";

/** Type-safe pub/sub topics for bootstrap and DAL entity change events. */
export type PubSubTopics = {
  PING_SENT: [{ pingSent: { message: string; timestamp: string } }];
  AUDITEVENT_CHANGED: [{ auditEventChanged: EntityChangeEventPayload }];
  CATEGORY_CHANGED: [{ categoryChanged: EntityChangeEventPayload }];
  ITEM_CHANGED: [{ itemChanged: EntityChangeEventPayload }];
  ITEMDETAIL_CHANGED: [{ itemDetailChanged: EntityChangeEventPayload }];
  ITEMTAG_CHANGED: [{ itemTagChanged: EntityChangeEventPayload }];
  ORDER_CHANGED: [{ orderChanged: EntityChangeEventPayload }];
  ORDERLINE_CHANGED: [{ orderLineChanged: EntityChangeEventPayload }];
  TAG_CHANGED: [{ tagChanged: EntityChangeEventPayload }];
};

export const pubsub = createAppPubSub<PubSubTopics>();
export type PubSub = typeof pubsub;
