// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import type { RelationDescriptor } from "@corpdk/dal-core";
import type { Table } from "drizzle-orm";
import { phase5Widgets } from "../../../db/schema/index.js";



const phase5WidgetsRelations: RelationDescriptor[] = [];



export const RELATION_DESCRIPTORS_BY_TABLE = new Map<Table, RelationDescriptor[]>([
  [phase5Widgets, phase5WidgetsRelations],
]);
