// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { eq, inArray } from "drizzle-orm";
import {
  assertFilterBulkCap,
  assertFilterBulkConfirm,
  assertValidUuid,
  CHANGE_EVENT_ID_CAP,
  createUserError,
  CURSOR_VERSION,
  errorPayload,
  mapDriverError,
  parseDateTime,
  QueryEngine,
  resolveActorId,
  resolveBulkAtomic,
  resolveBulkFilterMax,
  resolveColumnProjectionFromInfo,
  resolveFilterBudget,
  serializeDateTime,
  successPayload,
  validateColumnConstraints,
  ValidationError,
  type BulkMutationResult,
  type ColumnConstraintMeta,
  type ColumnDescriptor,
  type EntityChangeEventPayload,
  type FilterAST,
  type RelationDescriptor,
  type RelationProjectionHint,
  type RepositoryContext,
  type ResolvedSortKey,
  type SortInput,
} from "@corpdk/dal-core";
import type { GraphQLResolveInfo } from "graphql";
import { db } from "../../../db/index.js";
import { phase5Widgets } from "../../../db/schema/index.js";
import { RELATION_DESCRIPTORS_BY_TABLE } from "./generated-relation-descriptors.js";

const table = phase5Widgets;
const FILTER_BUDGET = resolveFilterBudget({ maxDepth: 2, maxNodes: 50 });
const BULK_FILTER_MAX = resolveBulkFilterMax();

const COLUMN_DESCRIPTORS: ColumnDescriptor[] = [
  { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: table.id },
  { graphqlName: "code", drizzleKey: "code", kind: "varchar" as const, column: table.code },
  { graphqlName: "qty", drizzleKey: "qty", kind: "integer" as const, column: table.qty },
  { graphqlName: "note", drizzleKey: "note", kind: "text" as const, column: table.note },
  { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: table.createdAt },
  { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: table.updatedAt },
  { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: table.createdBy },
  { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: table.updatedBy },
];

const RELATION_DESCRIPTORS = RELATION_DESCRIPTORS_BY_TABLE.get(table)!;

const RELATION_PROJECTION_HINTS: RelationProjectionHint[] = [];

const queryEngine = new QueryEngine<typeof table.$inferSelect>(
  {
    db,
    table,
    columns: COLUMN_DESCRIPTORS,
    relations: RELATION_DESCRIPTORS,
    softDelete: false,
    filterBudget: FILTER_BUDGET,
    entityGraphqlName: "Phase5Widget",
    cursorVersion: CURSOR_VERSION,
  },
  db,
  {
    ID: "id",
    CODE: "code",
    QTY: "qty",
    NOTE: "note",
    CREATED_AT: "createdAt",
    UPDATED_AT: "updatedAt",
    CREATED_BY: "createdBy",
    UPDATED_BY: "updatedBy",
  },
);

export type Phase5WidgetRecord = {
  id: string;
  code: string;
  qty: number;
  note: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type Phase5WidgetCreateInput = {
  code: string;
  qty: number;
  note: string;
};

export type Phase5WidgetUpdateInput = Partial<Phase5WidgetCreateInput>;

export type Phase5WidgetFilter = FilterAST;

const COLUMN_CONSTRAINTS: ColumnConstraintMeta[] = [
  { graphqlName: "code", drizzleKey: "code", maxLength: 12 },
  { graphqlName: "qty", drizzleKey: "qty", minExclusive: 0 },
];

function validateCreateInput(input: Phase5WidgetCreateInput) {
  validateColumnConstraints(input as Record<string, unknown>, COLUMN_CONSTRAINTS, "create");
}

function validateUpdateInput(input: Phase5WidgetUpdateInput) {
  validateColumnConstraints(input as Record<string, unknown>, COLUMN_CONSTRAINTS, "update");
}


function mapRow(row: typeof table.$inferSelect): Phase5WidgetRecord {
  return {
    id: row.id,
    code: row.code,
    qty: row.qty,
    note: row.note,
    createdAt: serializeDateTime(row.createdAt)!,
    updatedAt: serializeDateTime(row.updatedAt)!,
    createdBy: row.createdBy,
    updatedBy: row.updatedBy,
  };
}

function cursorValuesFromRow(row: typeof table.$inferSelect, resolvedSort: ResolvedSortKey[]): unknown[] {
  return resolvedSort.map((s) => {
    switch (s.drizzleKey) {
      case "createdAt":
        return serializeDateTime(row.createdAt)!;
      case "updatedAt":
        return serializeDateTime(row.updatedAt)!;
      default:
        return row[s.drizzleKey as keyof typeof row];
    }
  });
}

function cursorValuesToDb(values: unknown[], resolvedSort: ResolvedSortKey[]): unknown[] {
  return values.map((value, index) => {
    switch (resolvedSort[index]?.drizzleKey) {
      case "createdAt":
        return new Date(value as string);
      case "updatedAt":
        return new Date(value as string);
      default:
        return value;
    }
  });
}

function columnProjectionFromInfo(
  info: GraphQLResolveInfo | undefined,
  sortDrizzleKeys?: string[],
) {
  if (!info) return null;
  return resolveColumnProjectionFromInfo(
    info,
    "Phase5Widget",
    COLUMN_DESCRIPTORS,
    false,
    RELATION_PROJECTION_HINTS,
    sortDrizzleKeys,
  );
}

export class GeneratedPhase5WidgetRepository {
  mapRow = mapRow;

  async findById(
    id: string,
    opts?: { includeDeleted?: boolean | null },
    info?: GraphQLResolveInfo,
  ): Promise<Phase5WidgetRecord | null> {
    assertValidUuid(id);
    const projection = columnProjectionFromInfo(info);
    const rows = await queryEngine.findByIds([id], opts?.includeDeleted, projection);
    if (rows.length === 0) return null;
    return mapRow(rows[0]);
  }

  async findByIds(ids: string[], opts?: { includeDeleted?: boolean | null }): Promise<Phase5WidgetRecord[]> {
    const rows = await queryEngine.findByIds(ids, opts?.includeDeleted);
    return rows.map(mapRow);
  }



  async list(
    args: {
      filter?: Phase5WidgetFilter | null;
      sort?: SortInput[] | null;
      limit?: number | null;
      includeDeleted?: boolean | null;
    },
    info?: GraphQLResolveInfo,
  ): Promise<Phase5WidgetRecord[]> {
    const resolvedSort = queryEngine.resolveSort(args.sort);
    const projection = columnProjectionFromInfo(
      info,
      resolvedSort.map((s) => s.drizzleKey),
    );
    return (await queryEngine.list(args, mapRow, projection)) as Phase5WidgetRecord[];
  }

  async count(args: {
    filter?: Phase5WidgetFilter | null;
    includeDeleted?: boolean | null;
  }): Promise<number> {
    return queryEngine.count(args);
  }

  async listConnection(
    args: {
      filter?: Phase5WidgetFilter | null;
      sort?: SortInput[] | null;
      first?: number | null;
      after?: string | null;
      last?: number | null;
      before?: string | null;
      includeDeleted?: boolean | null;
    },
    info?: GraphQLResolveInfo,
  ) {
    const resolvedSort = queryEngine.resolveSort(args.sort);
    const projection = columnProjectionFromInfo(
      info,
      resolvedSort.map((s) => s.drizzleKey),
    );
    return queryEngine.listConnection(
      args,
      mapRow,
      cursorValuesFromRow,
      cursorValuesToDb,
      projection,
    );
  }

  async create(input: Phase5WidgetCreateInput, ctx: RepositoryContext, conn: typeof db = db) {
    try {
      validateCreateInput(input);
      const actor = resolveActorId(ctx.actorId);
      const now = new Date();
      const values = {
      code: input.code,
      qty: input.qty,
      note: input.note,
        createdAt: now,
        updatedAt: now,
        createdBy: actor,
        updatedBy: actor,
      };
      const inserted = await conn.insert(table).values(values).returning();
      const row = mapRow(inserted[0]);
      return successPayload({ phase5Widget: row });
    } catch (err) {
      if (err instanceof ValidationError) {
        return errorPayload({ phase5Widget: null }, [createUserError("VALIDATION_FAILED", err.message, { field: err.field })]);
      }
      return errorPayload({ phase5Widget: null }, [mapDriverError(err, "postgresql")]);
    }
  }

  async update(id: string, input: Phase5WidgetUpdateInput, ctx: RepositoryContext, conn: typeof db = db) {
    try {
      assertValidUuid(id);
      validateUpdateInput(input);
      const actor = resolveActorId(ctx.actorId);
      const set: Partial<typeof table.$inferInsert> = {
        updatedAt: new Date(),
        updatedBy: actor,
      };
    if (input.code !== undefined) {
    set.code = input.code;
  }
    if (input.qty !== undefined) {
    set.qty = input.qty;
  }
    if (input.note !== undefined) {
    set.note = input.note;
  }
      const updated = await conn.update(table).set(set).where(eq(table.id, id)).returning();
      if (updated.length === 0) {
        return errorPayload({ phase5Widget: null }, [createUserError("NOT_FOUND", "Phase5Widget not found", { id })]);
      }
      return successPayload({ phase5Widget: mapRow(updated[0]) });
    } catch (err) {
      if (err instanceof ValidationError) {
        return errorPayload({ phase5Widget: null }, [createUserError("VALIDATION_FAILED", err.message, { field: err.field })]);
      }
      return errorPayload({ phase5Widget: null }, [mapDriverError(err, "postgresql")]);
    }
  }

  async delete(id: string, ctx: RepositoryContext, conn: typeof db = db) {
    try {
      assertValidUuid(id);
      const deleted = await conn.delete(table).where(eq(table.id, id)).returning({ id: table.id });
      if (deleted.length === 0) {
        return errorPayload({ success: false }, [createUserError("NOT_FOUND", "Phase5Widget not found", { id })]);
      }
      return successPayload({ success: true });
    } catch (err) {
      return errorPayload({ success: false }, [mapDriverError(err, "postgresql")]);
    }
  }

  async bulkCreate(inputs: Phase5WidgetCreateInput[], ctx: RepositoryContext, atomic?: boolean | null) {
    const isAtomic = resolveBulkAtomic(inputs.length, atomic);
    if (isAtomic) {
      return db.transaction(async (tx) => {
        const items: Phase5WidgetRecord[] = [];
        for (const input of inputs) {
          const result = await this.create(input, ctx, tx);
          if (result.userErrors.length > 0) throw new ValidationError(result.userErrors[0]!.message);
          if (result.phase5Widget) items.push(result.phase5Widget);
        }
        return { items, userErrors: [] as const };
      }).catch((err) => {
        if (err instanceof ValidationError) {
          return { successCount: 0, failureCount: inputs.length, userErrors: [createUserError("VALIDATION_FAILED", err.message)] } satisfies BulkMutationResult;
        }
        throw err;
      });
    }
    const items: Phase5WidgetRecord[] = [];
    const userErrors: BulkMutationResult["userErrors"] = [];
    let successCount = 0;
    for (const input of inputs) {
      const result = await this.create(input, ctx);
      if (result.phase5Widget && result.userErrors.length === 0) {
        items.push(result.phase5Widget);
        successCount += 1;
      } else {
        userErrors.push(...result.userErrors);
      }
    }
    return { successCount, failureCount: inputs.length - successCount, userErrors };
  }

  async bulkUpdate(
    updates: Array<{ id: string; input: Phase5WidgetUpdateInput }>,
    ctx: RepositoryContext,
    atomic?: boolean | null,
  ) {
    const isAtomic = resolveBulkAtomic(updates.length, atomic);
    if (isAtomic) {
      return db.transaction(async (tx) => {
        const items: Phase5WidgetRecord[] = [];
        for (const entry of updates) {
          const result = await this.update(entry.id, entry.input, ctx, tx);
          if (result.userErrors.length > 0) throw new ValidationError(result.userErrors[0]!.message);
          if (result.phase5Widget) items.push(result.phase5Widget);
        }
        return { items, userErrors: [] as const };
      }).catch((err) => {
        if (err instanceof ValidationError) {
          return { successCount: 0, failureCount: updates.length, userErrors: [createUserError("VALIDATION_FAILED", err.message)] } satisfies BulkMutationResult;
        }
        throw err;
      });
    }
    const items: Phase5WidgetRecord[] = [];
    const userErrors: BulkMutationResult["userErrors"] = [];
    let successCount = 0;
    for (const entry of updates) {
      const result = await this.update(entry.id, entry.input, ctx);
      if (result.phase5Widget && result.userErrors.length === 0) {
        items.push(result.phase5Widget);
        successCount += 1;
      } else {
        userErrors.push(...result.userErrors.map((e) => ({ ...e, id: e.id ?? entry.id })));
      }
    }
    return { successCount, failureCount: updates.length - successCount, userErrors };
  }

  async bulkUpdateByFilter(
    filter: Phase5WidgetFilter,
    input: Phase5WidgetUpdateInput,
    ctx: RepositoryContext,
    confirmUpdateAll?: boolean | null,
  ): Promise<BulkMutationResult> {
    assertFilterBulkConfirm(filter, confirmUpdateAll, "confirmUpdateAll");
    const where = queryEngine.buildWhere(filter);
    if (!where) throw new ValidationError("Filter required", ["filter"]);
    const actor = resolveActorId(ctx.actorId);
    const set: Partial<typeof table.$inferInsert> = {
      updatedAt: new Date(),
      updatedBy: actor,
    };
    if (input.code !== undefined) {
    set.code = input.code;
  }
    if (input.qty !== undefined) {
    set.qty = input.qty;
  }
    if (input.note !== undefined) {
    set.note = input.note;
  }
    return db.transaction(async (tx) => {
      const matched = await tx.select({ id: table.id }).from(table).where(where).for("update");
      assertFilterBulkCap(matched.length, BULK_FILTER_MAX);
      const ids = matched.map((row) => row.id);
      if (ids.length === 0) {
        return { successCount: 0, failureCount: 0, userErrors: [] };
      }
      const updated = await tx.update(table).set(set).where(inArray(table.id, ids)).returning({ id: table.id });
      return { successCount: updated.length, failureCount: 0, userErrors: [] };
    });
  }

  async bulkDelete(ids: string[], ctx: RepositoryContext, atomic?: boolean | null) {
    const isAtomic = resolveBulkAtomic(ids.length, atomic);
    if (isAtomic) {
      return db.transaction(async (tx) => {
        let count = 0;
        for (const id of ids) {
          const result = await this.delete(id, ctx, tx);
          if (!result.success) throw new ValidationError(result.userErrors[0]?.message ?? "Delete failed");
          count += 1;
        }
        return { count, userErrors: [] as const };
      }).catch((err) => {
        if (err instanceof ValidationError) {
          return { successCount: 0, failureCount: ids.length, userErrors: [createUserError("VALIDATION_FAILED", err.message)] } satisfies BulkMutationResult;
        }
        throw err;
      });
    }
    const userErrors: BulkMutationResult["userErrors"] = [];
    let successCount = 0;
    for (const id of ids) {
      const result = await this.delete(id, ctx);
      if (result.success) successCount += 1;
      else userErrors.push(...result.userErrors.map((e) => ({ ...e, id: e.id ?? id })));
    }
    return { successCount, failureCount: ids.length - successCount, userErrors };
  }

  async bulkDeleteByFilter(
    filter: Phase5WidgetFilter,
    ctx: RepositoryContext,
    confirmDeleteAll?: boolean | null,
  ): Promise<BulkMutationResult> {
    assertFilterBulkConfirm(filter, confirmDeleteAll, "confirmDeleteAll");
    const where = queryEngine.buildWhere(filter);
    if (!where) throw new ValidationError("Filter required", ["filter"]);
    return db.transaction(async (tx) => {
      const matched = await tx.select({ id: table.id }).from(table).where(where).for("update");
      assertFilterBulkCap(matched.length, BULK_FILTER_MAX);
      const ids = matched.map((row) => row.id);
      if (ids.length === 0) {
        return { successCount: 0, failureCount: 0, userErrors: [] };
      }
      const deleted = await tx.delete(table).where(inArray(table.id, ids)).returning({ id: table.id });
      return { successCount: deleted.length, failureCount: 0, userErrors: [] };
    });
  }

  toChangeEvent(operation: EntityChangeEventPayload["operation"], ids: string[]): EntityChangeEventPayload {
    const count = ids.length;
    const isTruncated = count > CHANGE_EVENT_ID_CAP;
    return {
      operation,
      ids: isTruncated ? [] : ids,
      isTruncated,
      count,
    };
  }
}
