import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadDalConfig, type CodegenOptions } from "./config.js";
import { loadEntities } from "./model.js";
import { generateSchemaModule } from "./generators/sdl.js";
import { generateRepository, generateRepositoryIndex } from "./generators/repository.js";
import { generatePubSub } from "./generators/pubsub.js";
import { generateResolvers } from "./generators/resolvers.js";

const GENERATED_BANNER = "// AUTO-GENERATED by @corpdk/dal-codegen — do not edit\n";

function writeFile(path: string, content: string): void {
  writeFileSync(path, content.endsWith("\n") ? content : content + "\n", "utf-8");
}

export async function runDalCodegen(options: CodegenOptions): Promise<void> {
  const config = loadDalConfig(join(options.packageRoot, options.configPath));
  const schemaPath = join(options.packageRoot, options.schemaPath);
  const outputDir = join(options.packageRoot, options.outputDir);

  const entities = await loadEntities(schemaPath, config.strict);
  if (entities.length === 0) {
    throw new Error(`No PersistedEntity tables found in ${schemaPath}`);
  }

  if (existsSync(outputDir)) {
    rmSync(outputDir, { recursive: true, force: true });
  }

  const repoDir = join(outputDir, "repositories");
  const resolverDir = join(outputDir, "resolvers");
  mkdirSync(repoDir, { recursive: true });
  mkdirSync(resolverDir, { recursive: true });

  writeFile(join(outputDir, "generated-schema.ts"), generateSchemaModule(entities));
  writeFile(join(outputDir, "generated-pubsub.ts"), generatePubSub(entities));

  for (const entity of entities) {
    writeFile(
      join(repoDir, `generated-${entity.fieldBasename}.repository.ts`),
      generateRepository(entity, entities, config),
    );
  }
  writeFile(join(repoDir, "index.ts"), generateRepositoryIndex(entities));
  writeFile(join(resolverDir, "generated-resolvers.ts"), generateResolvers(entities));

  writeFile(
    join(outputDir, "index.ts"),
    `${GENERATED_BANNER}export * from "./generated-schema.js";
export * from "./generated-pubsub.js";
export * from "./repositories/index.js";
export * from "./resolvers/generated-resolvers.js";
`,
  );

  writeFile(
    join(outputDir, "manifest.json"),
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        entities: entities.map((e) => ({
          exportName: e.exportName,
          graphqlType: e.graphqlType,
          auditProfile: e.auditProfile,
          deleteStrategy: e.deleteStrategy,
        })),
      },
      null,
      2,
    ),
  );

  console.log(`dal-codegen: generated ${entities.length} entity(s) → ${options.outputDir}`);
}
