import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  loadDalConfig,
  type CodegenOptions,
  type DalCodegenMode,
} from "./config.js";
import {
  formatLintViolations,
  lintExitCode,
  runEntityLint,
} from "./entity-lint.js";
import { loadEntities, type EntityModel } from "./model.js";
import { generateSchemaModule } from "./generators/sdl.js";
import {
  generateRelationDescriptorsModule,
  generateRepository,
  generateRepositoryIndex,
} from "./generators/repository.js";
import { generatePubSub } from "./generators/pubsub.js";
import { generateGraphqlCodegenMappersModule } from "./generators/graphql-mappers.js";
import { generateEntityRecordsModule } from "./generators/entity-records.js";
import { generateResolvers } from "./generators/resolvers.js";
import { generateAppBootstrapFiles } from "./generators/app-bootstrap.js";
import { generateInputZodModule } from "./generators/input-zod.js";

const GENERATED_BANNER =
  "// AUTO-GENERATED by @corpdk/dal-codegen — do not edit\n";

function writeFile(path: string, content: string): void {
  writeFileSync(
    path,
    content.endsWith("\n") ? content : content + "\n",
    "utf-8",
  );
}

function resolvePaths(options: CodegenOptions) {
  return {
    schemaPath: join(options.packageRoot, options.schemaPath),
    outputDir: join(options.packageRoot, options.outputDir),
    schemaOutputFile: join(options.packageRoot, options.schemaOutputPath),
    entityRecordsFile: join(
      options.packageRoot,
      options.entityRecordsOutputPath ?? "src/generated/entity-records.ts",
    ),
    mappersFile: join(
      options.packageRoot,
      options.mappersOutputPath ?? "src/generated/graphql-codegen.mappers.ts",
    ),
    configPath: join(options.packageRoot, options.configPath),
  };
}

async function loadEntitiesForCodegen(options: CodegenOptions): Promise<{
  entities: EntityModel[];
  config: ReturnType<typeof loadDalConfig>;
}> {
  const paths = resolvePaths(options);
  const config = loadDalConfig(paths.configPath);

  const entities = await loadEntities(paths.schemaPath, config.strict);
  if (entities.length === 0) {
    throw new Error(`No PersistedEntity tables found in ${paths.schemaPath}`);
  }

  if (config.strict) {
    const lintResult = await runEntityLint({
      packageRoot: options.packageRoot,
      schemaPath: options.schemaPath,
      configPath: options.configPath,
    });
    if (lintExitCode(lintResult.violations) !== 0) {
      throw new Error(
        `entity lint failed (strict mode):\n${formatLintViolations(lintResult.violations)}`,
      );
    }
  }

  return { entities, config };
}

/** Phase 1: schema SDL, entity *Record types, graphql-codegen mappers (no dal/ wipe). */
export async function runDalCodegenSchema(
  options: CodegenOptions,
): Promise<void> {
  const { entities } = await loadEntitiesForCodegen(options);
  const paths = resolvePaths(options);

  mkdirSync(dirname(paths.schemaOutputFile), { recursive: true });
  writeFile(paths.schemaOutputFile, generateSchemaModule(entities));
  mkdirSync(dirname(paths.entityRecordsFile), { recursive: true });
  writeFile(paths.entityRecordsFile, generateEntityRecordsModule(entities));
  mkdirSync(dirname(paths.mappersFile), { recursive: true });
  writeFile(paths.mappersFile, generateGraphqlCodegenMappersModule(entities));

  console.log(
    `dal-codegen (schema): ${entities.length} entity(s) → ${options.schemaOutputPath}, ${options.entityRecordsOutputPath ?? "src/generated/entity-records.ts"}, ${options.mappersOutputPath ?? "src/generated/graphql-codegen.mappers.ts"}`,
  );
}

/** Phase 3: repositories, resolvers, pubsub under outputDir (wiped each run). */
export async function runDalCodegenImpl(
  options: CodegenOptions,
): Promise<void> {
  const { entities, config } = await loadEntitiesForCodegen(options);
  const paths = resolvePaths(options);

  if (existsSync(paths.outputDir)) {
    rmSync(paths.outputDir, { recursive: true, force: true });
  }

  const repoDir = join(paths.outputDir, "repositories");
  const resolverDir = join(paths.outputDir, "resolvers");
  mkdirSync(repoDir, { recursive: true });
  mkdirSync(resolverDir, { recursive: true });

  writeFile(
    join(paths.outputDir, "generated-pubsub.ts"),
    generatePubSub(entities),
  );
  writeFile(
    join(paths.outputDir, "repositories", "generated-relation-descriptors.ts"),
    generateRelationDescriptorsModule(entities),
  );

  for (const entity of entities) {
    writeFile(
      join(repoDir, `generated-${entity.fieldBasename}.repository.ts`),
      generateRepository(entity, entities, config),
    );
  }
  writeFile(join(repoDir, "index.ts"), generateRepositoryIndex(entities));
  writeFile(
    join(resolverDir, "generated-resolvers.ts"),
    generateResolvers(entities),
  );

  writeFile(
    join(paths.outputDir, "input-zod.ts"),
    `${GENERATED_BANNER}${generateInputZodModule(entities)}`,
  );

  writeFile(
    join(paths.outputDir, "index.ts"),
    `${GENERATED_BANNER}export * from "./generated-pubsub.js";
export * from "./repositories/index.js";
export * from "./resolvers/generated-resolvers.js";
export * from "./input-zod.js";
`,
  );

  writeFile(
    join(paths.outputDir, "manifest.json"),
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        entities: entities.map((e) => ({
          exportName: e.exportName,
          graphqlType: e.graphqlType,
          auditProfile: e.auditProfile,
          deleteStrategy: e.deleteStrategy,
        })),
      },
      null,
      2,
    ),
  );

  console.log(
    `dal-codegen (impl): ${entities.length} entity(s) → ${options.outputDir}`,
  );
}

/** Writes src/schema.ts, src/index.ts, and src/db/index.ts (Yoga entry bootstrap). */
export async function runDalCodegenBootstrap(
  options: CodegenOptions,
): Promise<void> {
  const { schemaTs, indexTs, dbIndexTs } = generateAppBootstrapFiles();

  for (const rel of [
    "src/schema.ts",
    "src/index.ts",
    "src/db/index.ts",
  ] as const) {
    const filePath = join(options.packageRoot, rel);
    mkdirSync(dirname(filePath), { recursive: true });
    writeFile(
      filePath,
      rel === "src/schema.ts"
        ? schemaTs
        : rel === "src/index.ts"
          ? indexTs
          : dbIndexTs,
    );
  }

  console.log(
    `dal-codegen (bootstrap): Yoga entry files → src/schema.ts, src/index.ts, src/db/index.ts`,
  );
}

export async function runDalCodegen(options: CodegenOptions): Promise<void> {
  const mode: DalCodegenMode = options.mode ?? "all";
  if (mode === "bootstrap") {
    await runDalCodegenBootstrap(options);
    return;
  }
  if (mode === "schema" || mode === "all") {
    await runDalCodegenSchema(options);
  }
  if (mode === "impl" || mode === "all") {
    await runDalCodegenImpl(options);
  }
}
