packages:
  - templates/*
  - engines/*
  - libraries/*
  - packages/*

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - couchbase
  - esbuild
  - msw
  - prisma
