// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
export type AuditEventRecord = {
  id: string;
  action: string;
  payload: string;
  createdAt: string;
  createdBy: string;
};

export type CategoryRecord = {
  id: string;
  name: string;
  description: string | null;
  isVisible: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type ItemDetailRecord = {
  id: string;
  itemId: string;
  specifications: string | null;
  warrantyNotes: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type ItemRecord = {
  id: string;
  categoryId: string;
  name: string;
  description: string | null;
  isActive: boolean;
  hasAttachments: boolean;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type ItemTagRecord = {
  id: string;
  itemId: string;
  tagId: string;
  assignedAt: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type LabelRecord = {
  id: string;
  label: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type OrderLineRecord = {
  id: string;
  orderId: string;
  itemId: string;
  quantity: number;
  sku: string;
  description: string | null;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type OrderRecord = {
  id: string;
  userId: string;
  customerName: string;
  notes: string | null;
  status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type TagRecord = {
  id: string;
  label: string;
  createdAt: string;
  createdBy: string;
};

export type UserLabelRecord = {
  id: string;
  userId: string;
  labelId: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type UserRecord = {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};
