// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
/** Passed to graphql-codegen typescript-resolvers `mappers`. */
export const graphqlCodegenMappers = {
  AuditEvent: "../entity-records.js#AuditEventRecord",
  Category: "../entity-records.js#CategoryRecord",
  ItemDetail: "../entity-records.js#ItemDetailRecord",
  Item: "../entity-records.js#ItemRecord",
  ItemTag: "../entity-records.js#ItemTagRecord",
  Label: "../entity-records.js#LabelRecord",
  OrderLine: "../entity-records.js#OrderLineRecord",
  Order: "../entity-records.js#OrderRecord",
  Tag: "../entity-records.js#TagRecord",
  UserLabel: "../entity-records.js#UserLabelRecord",
  User: "../entity-records.js#UserRecord",
} as const satisfies Record<string, string>;
