import type { EntityModel } from "../../model.js";

/** Minimal Item-like entity for SDL snapshot tests. */
export const itemFixture: EntityModel = {
  exportName: "items",
  tableName: "items",
  graphqlType: "Item",
  fieldBasename: "item",
  listField: "items",
  auditProfile: "full",
  deleteStrategy: "soft",
  tableComment: "Customer-facing data items; soft-deleted rows retained per retention policy.",
  sourceFile: "items.ts",
  columns: [
    {
      drizzleKey: "id",
      physicalName: "id",
      graphqlName: "id",
      kind: "uuid",
      notNull: true,
      hasDefault: true,
      comment: "Surrogate primary key.",
      isServerManaged: true,
      isBusiness: false,
    },
    {
      drizzleKey: "name",
      physicalName: "name",
      graphqlName: "name",
      kind: "varchar",
      notNull: true,
      hasDefault: false,
      comment: "Display name of the item.",
      isServerManaged: false,
      isBusiness: true,
    },
    {
      drizzleKey: "description",
      physicalName: "description",
      graphqlName: "description",
      kind: "text",
      notNull: false,
      hasDefault: false,
      comment: "Optional longer description of the item.",
      isServerManaged: false,
      isBusiness: true,
    },
    {
      drizzleKey: "isActive",
      physicalName: "is_active",
      graphqlName: "isActive",
      kind: "boolean",
      notNull: true,
      hasDefault: true,
      comment: "Whether the item is currently active.",
      isServerManaged: false,
      isBusiness: true,
    },
    {
      drizzleKey: "deletedAt",
      physicalName: "deleted_at",
      graphqlName: "deletedAt",
      kind: "timestamptz",
      notNull: false,
      hasDefault: false,
      comment: "Soft-delete timestamp (UTC); NULL = active row.",
      isServerManaged: true,
      isBusiness: false,
    },
    {
      drizzleKey: "deletedBy",
      physicalName: "deleted_by",
      graphqlName: "deletedBy",
      kind: "text",
      notNull: false,
      hasDefault: false,
      comment: "Actor ID who soft-deleted this row.",
      isServerManaged: true,
      isBusiness: false,
    },
    {
      drizzleKey: "createdAt",
      physicalName: "created_at",
      graphqlName: "createdAt",
      kind: "timestamptz",
      notNull: true,
      hasDefault: true,
      comment: "Row creation time (UTC).",
      isServerManaged: true,
      isBusiness: false,
    },
    {
      drizzleKey: "updatedAt",
      physicalName: "updated_at",
      graphqlName: "updatedAt",
      kind: "timestamptz",
      notNull: true,
      hasDefault: true,
      comment: "Last update time (UTC).",
      isServerManaged: true,
      isBusiness: false,
    },
    {
      drizzleKey: "createdBy",
      physicalName: "created_by",
      graphqlName: "createdBy",
      kind: "text",
      notNull: true,
      hasDefault: false,
      comment: "Actor ID from request context; never client-supplied.",
      isServerManaged: true,
      isBusiness: false,
    },
    {
      drizzleKey: "updatedBy",
      physicalName: "updated_by",
      graphqlName: "updatedBy",
      kind: "text",
      notNull: true,
      hasDefault: false,
      comment: "Actor ID from request context on last update.",
      isServerManaged: true,
      isBusiness: false,
    },
  ],
};
