import { buildSchema, validateSchema } from "graphql";
import { describe, expect, it } from "vitest";
import { buildDalGraphQLSchema } from "../schema-builder.js";
import { buildSchemaRegistry } from "../schema-registry.js";
import {
  escapeSdlForTemplateLiteral,
  generateMergedTypeDefs,
  generateSchemaModule,
} from "../sdl.js";
import { itemFixture } from "./sdl.fixture.js";

describe("schema builder", () => {
  const entities = [itemFixture];

  it("builds a valid GraphQL schema for the item fixture", () => {
    const schema = buildDalGraphQLSchema(entities);
    expect(validateSchema(schema)).toEqual([]);
    expect(schema.getQueryType()?.getFields().hello).toBeDefined();
    expect(schema.getQueryType()?.getFields().status).toBeDefined();
    expect(schema.getQueryType()?.getFields().items).toBeDefined();
    expect(schema.getMutationType()?.getFields().ping).toBeDefined();
    expect(schema.getMutationType()?.getFields().createItem).toBeDefined();
    expect(schema.getSubscriptionType()?.getFields().pingSent).toBeDefined();
    expect(schema.getSubscriptionType()?.getFields().itemChanged).toBeDefined();
  });

  it("emits only entity-referenced scalars and filters in the registry", () => {
    const registry = buildSchemaRegistry(entities);
    expect(registry.types.has("DateTime")).toBe(true);
    expect(registry.types.has("Date")).toBe(false);
    expect(registry.types.has("BigInt")).toBe(false);
    expect(registry.types.has("StringFilter")).toBe(true);
    expect(registry.types.has("SortDirection")).toBe(true);
  });

  it("prints merged SDL with root types and entity surface", () => {
    const merged = generateMergedTypeDefs(entities);
    expect(merged).toMatchSnapshot();
  });

  it("printed SDL is parseable and valid", () => {
    const sdl = generateMergedTypeDefs(entities);
    const schema = buildSchema(sdl);
    expect(validateSchema(schema)).toEqual([]);
  });

  it("escapes backticks and ${ for template literal embedding", () => {
    const sdl = "line with `backtick` and ${not interpolation}";
    expect(escapeSdlForTemplateLiteral(sdl)).toBe(
      "line with \\`backtick\\` and \\${not interpolation}",
    );
    expect(escapeSdlForTemplateLiteral("a\\b")).toBe("a\\\\b");
  });

  it("emits a TypeScript module whose typeDefs build a valid schema", () => {
    const merged = generateMergedTypeDefs(entities);
    const moduleSource = generateSchemaModule(entities);
    expect(moduleSource).toMatch(/^\/\/ AUTO-GENERATED by @corpdk\/dal-codegen/);
    expect(moduleSource).toContain("export const typeDefs = `");
    const open = moduleSource.indexOf("export const typeDefs = `") + "export const typeDefs = `".length;
    const close = moduleSource.lastIndexOf("`;");
    expect(close).toBeGreaterThan(open);
    const embedded = moduleSource.slice(open, close);
    expect(embedded).toBe(escapeSdlForTemplateLiteral(merged));
    const schema = buildSchema(merged);
    expect(validateSchema(schema)).toEqual([]);
    expect(schema.getQueryType()?.getFields().items).toBeDefined();
  });
});
