import { buildSchema, validateSchema } from "graphql";
import { describe, expect, it } from "vitest";
import { buildDalGraphQLSchema } from "../schema-builder.js";
import { buildSchemaRegistry } from "../schema-registry.js";
import { generateMergedTypeDefs, generateSchemaModule } from "../sdl.js";
import { itemFixture } from "./sdl.fixture.js";

describe("schema builder", () => {
  const entities = [itemFixture];

  it("builds a valid GraphQL schema for the item fixture", () => {
    const schema = buildDalGraphQLSchema(entities);
    expect(validateSchema(schema)).toEqual([]);
    expect(schema.getQueryType()?.getFields().hello).toBeDefined();
    expect(schema.getQueryType()?.getFields().status).toBeDefined();
    expect(schema.getQueryType()?.getFields().items).toBeDefined();
    expect(schema.getMutationType()?.getFields().ping).toBeDefined();
    expect(schema.getMutationType()?.getFields().createItem).toBeDefined();
    expect(schema.getSubscriptionType()?.getFields().pingSent).toBeDefined();
    expect(schema.getSubscriptionType()?.getFields().itemChanged).toBeDefined();
  });

  it("emits only entity-referenced scalars and filters in the registry", () => {
    const registry = buildSchemaRegistry(entities);
    expect(registry.types.has("DateTime")).toBe(true);
    expect(registry.types.has("Date")).toBe(false);
    expect(registry.types.has("BigInt")).toBe(false);
    expect(registry.types.has("StringFilter")).toBe(true);
    expect(registry.types.has("SortDirection")).toBe(true);
  });

  it("prints merged SDL with root types and entity surface", () => {
    const merged = generateMergedTypeDefs(entities);
    expect(merged).toMatchSnapshot();
    expect(merged).toContain("type Query");
    expect(merged).toContain("type ServerStatus {");
    expect(merged).toContain("type PingResult {");
    expect(merged).toContain("type Item {");
    expect(merged).toContain("scalar DateTime");
    expect(merged).toContain("direction: SortDirection = ASC");
    expect(merged.match(/^enum SortDirection/gm)?.length).toBe(1);
  });

  it("printed SDL is parseable and valid", () => {
    const sdl = generateMergedTypeDefs(entities);
    const schema = buildSchema(sdl);
    expect(validateSchema(schema)).toEqual([]);
  });

  it("emits a TypeScript module whose typeDefs build a valid schema", () => {
    const moduleSource = generateSchemaModule(entities);
    expect(moduleSource).toMatch(/^\/\/ AUTO-GENERATED by @corpdk\/dal-codegen/);
    const typeDefsLine = moduleSource
      .split("\n")
      .find((line) => line.startsWith("export const typeDefs = "));
    expect(typeDefsLine).toBeDefined();
    const json = typeDefsLine!.slice("export const typeDefs = ".length, -1);
    const sdl = JSON.parse(json) as string;
    const schema = buildSchema(sdl);
    expect(validateSchema(schema)).toEqual([]);
    expect(schema.getQueryType()?.getFields().items).toBeDefined();
  });
});
