// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import type { RelationDescriptor } from "@corpdk/dal-core";
import type { Table } from "drizzle-orm";
import { auditEvents, categories, itemDetails, items, itemTags, orderLines, orders, tags } from "../../../db/schema/index.js";

const categories_itemsRel: RelationDescriptor = {
    fieldName: "items",
    kind: "one-to-many" as const,
    ownerFkDrizzleKey: undefined,
    childFkDrizzleKey: "categoryId",
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: items,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: items.id },
      { graphqlName: "categoryId", drizzleKey: "categoryId", kind: "uuid" as const, column: items.categoryId },
      { graphqlName: "name", drizzleKey: "name", kind: "varchar" as const, column: items.name },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: items.description },
      { graphqlName: "isActive", drizzleKey: "isActive", kind: "boolean" as const, column: items.isActive },
      { graphqlName: "hasAttachments", drizzleKey: "hasAttachments", kind: "boolean" as const, column: items.hasAttachments },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: items.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: items.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: items.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: items.updatedBy }
    ],
    childTable: items,
    childColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: items.id },
      { graphqlName: "categoryId", drizzleKey: "categoryId", kind: "uuid" as const, column: items.categoryId },
      { graphqlName: "name", drizzleKey: "name", kind: "varchar" as const, column: items.name },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: items.description },
      { graphqlName: "isActive", drizzleKey: "isActive", kind: "boolean" as const, column: items.isActive },
      { graphqlName: "hasAttachments", drizzleKey: "hasAttachments", kind: "boolean" as const, column: items.hasAttachments },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: items.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: items.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: items.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: items.updatedBy }
    ],
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: true,
    childSoftDelete: true,
    filterable: true,
  };

const itemDetails_itemRel: RelationDescriptor = {
    fieldName: "item",
    kind: "many-to-one" as const,
    ownerFkDrizzleKey: "itemId",
    childFkDrizzleKey: undefined,
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: items,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: items.id },
      { graphqlName: "categoryId", drizzleKey: "categoryId", kind: "uuid" as const, column: items.categoryId },
      { graphqlName: "name", drizzleKey: "name", kind: "varchar" as const, column: items.name },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: items.description },
      { graphqlName: "isActive", drizzleKey: "isActive", kind: "boolean" as const, column: items.isActive },
      { graphqlName: "hasAttachments", drizzleKey: "hasAttachments", kind: "boolean" as const, column: items.hasAttachments },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: items.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: items.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: items.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: items.updatedBy }
    ],
    childTable: undefined,
    childColumns: undefined,
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: true,
    childSoftDelete: false,
    filterable: true,
  };

const items_categoryRel: RelationDescriptor = {
    fieldName: "category",
    kind: "many-to-one" as const,
    ownerFkDrizzleKey: "categoryId",
    childFkDrizzleKey: undefined,
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: categories,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: categories.id },
      { graphqlName: "name", drizzleKey: "name", kind: "varchar" as const, column: categories.name },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: categories.description },
      { graphqlName: "isVisible", drizzleKey: "isVisible", kind: "boolean" as const, column: categories.isVisible },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: categories.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: categories.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: categories.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: categories.updatedBy }
    ],
    childTable: undefined,
    childColumns: undefined,
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: false,
    childSoftDelete: false,
    filterable: true,
  };

const items_detailRel: RelationDescriptor = {
    fieldName: "detail",
    kind: "one-to-one" as const,
    ownerFkDrizzleKey: undefined,
    childFkDrizzleKey: "itemId",
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: itemDetails,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: itemDetails.id },
      { graphqlName: "itemId", drizzleKey: "itemId", kind: "uuid" as const, column: itemDetails.itemId },
      { graphqlName: "specifications", drizzleKey: "specifications", kind: "text" as const, column: itemDetails.specifications },
      { graphqlName: "warrantyNotes", drizzleKey: "warrantyNotes", kind: "text" as const, column: itemDetails.warrantyNotes },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: itemDetails.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: itemDetails.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: itemDetails.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: itemDetails.updatedBy }
    ],
    childTable: undefined,
    childColumns: undefined,
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: false,
    childSoftDelete: false,
    filterable: true,
  };

const items_itemTagsRel: RelationDescriptor = {
    fieldName: "itemTags",
    kind: "one-to-many" as const,
    ownerFkDrizzleKey: undefined,
    childFkDrizzleKey: "itemId",
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: itemTags,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: itemTags.id },
      { graphqlName: "itemId", drizzleKey: "itemId", kind: "uuid" as const, column: itemTags.itemId },
      { graphqlName: "tagId", drizzleKey: "tagId", kind: "uuid" as const, column: itemTags.tagId },
      { graphqlName: "assignedAt", drizzleKey: "assignedAt", kind: "timestamptz" as const, column: itemTags.assignedAt },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: itemTags.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: itemTags.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: itemTags.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: itemTags.updatedBy }
    ],
    childTable: itemTags,
    childColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: itemTags.id },
      { graphqlName: "itemId", drizzleKey: "itemId", kind: "uuid" as const, column: itemTags.itemId },
      { graphqlName: "tagId", drizzleKey: "tagId", kind: "uuid" as const, column: itemTags.tagId },
      { graphqlName: "assignedAt", drizzleKey: "assignedAt", kind: "timestamptz" as const, column: itemTags.assignedAt },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: itemTags.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: itemTags.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: itemTags.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: itemTags.updatedBy }
    ],
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: false,
    childSoftDelete: false,
    filterable: true,
  };

const itemTags_itemRel: RelationDescriptor = {
    fieldName: "item",
    kind: "many-to-one" as const,
    ownerFkDrizzleKey: "itemId",
    childFkDrizzleKey: undefined,
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: items,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: items.id },
      { graphqlName: "categoryId", drizzleKey: "categoryId", kind: "uuid" as const, column: items.categoryId },
      { graphqlName: "name", drizzleKey: "name", kind: "varchar" as const, column: items.name },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: items.description },
      { graphqlName: "isActive", drizzleKey: "isActive", kind: "boolean" as const, column: items.isActive },
      { graphqlName: "hasAttachments", drizzleKey: "hasAttachments", kind: "boolean" as const, column: items.hasAttachments },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: items.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: items.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: items.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: items.updatedBy }
    ],
    childTable: undefined,
    childColumns: undefined,
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: true,
    childSoftDelete: false,
    filterable: true,
  };

const itemTags_tagRel: RelationDescriptor = {
    fieldName: "tag",
    kind: "many-to-one" as const,
    ownerFkDrizzleKey: "tagId",
    childFkDrizzleKey: undefined,
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: tags,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: tags.id },
      { graphqlName: "label", drizzleKey: "label", kind: "varchar" as const, column: tags.label },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: tags.createdAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: tags.createdBy }
    ],
    childTable: undefined,
    childColumns: undefined,
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: true,
    childSoftDelete: false,
    filterable: true,
  };

const orderLines_orderRel: RelationDescriptor = {
    fieldName: "order",
    kind: "many-to-one" as const,
    ownerFkDrizzleKey: "orderId",
    childFkDrizzleKey: undefined,
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: orders,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: orders.id },
      { graphqlName: "customerName", drizzleKey: "customerName", kind: "varchar" as const, column: orders.customerName },
      { graphqlName: "notes", drizzleKey: "notes", kind: "text" as const, column: orders.notes },
      { graphqlName: "status", drizzleKey: "status", kind: "enum" as const, column: orders.status },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: orders.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: orders.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: orders.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: orders.updatedBy }
    ],
    childTable: undefined,
    childColumns: undefined,
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: true,
    childSoftDelete: false,
    filterable: true,
  };

const orders_linesRel: RelationDescriptor = {
    fieldName: "lines",
    kind: "one-to-many" as const,
    ownerFkDrizzleKey: undefined,
    childFkDrizzleKey: "orderId",
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: orderLines,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: orderLines.id },
      { graphqlName: "orderId", drizzleKey: "orderId", kind: "uuid" as const, column: orderLines.orderId },
      { graphqlName: "sku", drizzleKey: "sku", kind: "varchar" as const, column: orderLines.sku },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: orderLines.description },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: orderLines.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: orderLines.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: orderLines.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: orderLines.updatedBy }
    ],
    childTable: orderLines,
    childColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: orderLines.id },
      { graphqlName: "orderId", drizzleKey: "orderId", kind: "uuid" as const, column: orderLines.orderId },
      { graphqlName: "sku", drizzleKey: "sku", kind: "varchar" as const, column: orderLines.sku },
      { graphqlName: "description", drizzleKey: "description", kind: "text" as const, column: orderLines.description },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: orderLines.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: orderLines.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: orderLines.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: orderLines.updatedBy }
    ],
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: false,
    childSoftDelete: false,
    filterable: true,
  };

const tags_itemTagsRel: RelationDescriptor = {
    fieldName: "itemTags",
    kind: "one-to-many" as const,
    ownerFkDrizzleKey: undefined,
    childFkDrizzleKey: "tagId",
    joinOwnerFkDrizzleKey: undefined,
    joinTargetFkDrizzleKey: undefined,
    targetTable: itemTags,
    targetColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: itemTags.id },
      { graphqlName: "itemId", drizzleKey: "itemId", kind: "uuid" as const, column: itemTags.itemId },
      { graphqlName: "tagId", drizzleKey: "tagId", kind: "uuid" as const, column: itemTags.tagId },
      { graphqlName: "assignedAt", drizzleKey: "assignedAt", kind: "timestamptz" as const, column: itemTags.assignedAt },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: itemTags.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: itemTags.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: itemTags.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: itemTags.updatedBy }
    ],
    childTable: itemTags,
    childColumns: [
      { graphqlName: "id", drizzleKey: "id", kind: "uuid" as const, column: itemTags.id },
      { graphqlName: "itemId", drizzleKey: "itemId", kind: "uuid" as const, column: itemTags.itemId },
      { graphqlName: "tagId", drizzleKey: "tagId", kind: "uuid" as const, column: itemTags.tagId },
      { graphqlName: "assignedAt", drizzleKey: "assignedAt", kind: "timestamptz" as const, column: itemTags.assignedAt },
      { graphqlName: "createdAt", drizzleKey: "createdAt", kind: "timestamptz" as const, column: itemTags.createdAt },
      { graphqlName: "updatedAt", drizzleKey: "updatedAt", kind: "timestamptz" as const, column: itemTags.updatedAt },
      { graphqlName: "createdBy", drizzleKey: "createdBy", kind: "text" as const, column: itemTags.createdBy },
      { graphqlName: "updatedBy", drizzleKey: "updatedBy", kind: "text" as const, column: itemTags.updatedBy }
    ],
    joinTable: undefined,
    joinColumns: undefined,
    targetSoftDelete: false,
    childSoftDelete: false,
    filterable: true,
  };

const auditEventsRelations: RelationDescriptor[] = [];

const categoriesRelations: RelationDescriptor[] = [
  categories_itemsRel,
];

const itemDetailsRelations: RelationDescriptor[] = [
  itemDetails_itemRel,
];

const itemsRelations: RelationDescriptor[] = [
  items_categoryRel,
  items_detailRel,
  items_itemTagsRel,
];

const itemTagsRelations: RelationDescriptor[] = [
  itemTags_itemRel,
  itemTags_tagRel,
];

const orderLinesRelations: RelationDescriptor[] = [
  orderLines_orderRel,
];

const ordersRelations: RelationDescriptor[] = [
  orders_linesRel,
];

const tagsRelations: RelationDescriptor[] = [
  tags_itemTagsRel,
];

categories_itemsRel.childRelations = itemsRelations;
itemDetails_itemRel.targetRelations = itemsRelations;
items_categoryRel.targetRelations = categoriesRelations;
items_detailRel.targetRelations = itemDetailsRelations;
items_itemTagsRel.childRelations = itemTagsRelations;
itemTags_itemRel.targetRelations = itemsRelations;
itemTags_tagRel.targetRelations = tagsRelations;
orderLines_orderRel.targetRelations = ordersRelations;
orders_linesRel.childRelations = orderLinesRelations;
tags_itemTagsRel.childRelations = itemTagsRelations;

export const RELATION_DESCRIPTORS_BY_TABLE = new Map<Table, RelationDescriptor[]>([
  [auditEvents, auditEventsRelations],
  [categories, categoriesRelations],
  [itemDetails, itemDetailsRelations],
  [items, itemsRelations],
  [itemTags, itemTagsRelations],
  [orderLines, orderLinesRelations],
  [orders, ordersRelations],
  [tags, tagsRelations],
]);
