// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { createAppPubSub } from "@corpdk/pub-sub";
import type { EntityChangeEventPayload } from "@corpdk/dal-core";

/** Type-safe pub/sub topics for bootstrap and DAL entity change events. */
export type PubSubTopics = {
  PING_SENT: [{ pingSent: { message: string; timestamp: string } }];
  PHASE5WIDGET_CHANGED: [{ phase5WidgetChanged: EntityChangeEventPayload }];
};

export const pubsub = createAppPubSub<PubSubTopics>();
export type PubSub = typeof pubsub;
