// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
export type Phase5ConstraintFixtureRecord = {
  id: string;
  label: string;
  quantity: number;
  note: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};
