import type { EntityModel } from "../model.js";
import { internalRecordColumns } from "./schema-utils.js";
import { tsTypeForColumn } from "./repository-scalars.js";

export function recordTypeDefinition(entity: EntityModel): string {
  const E = entity.graphqlType;
  const recordCols = internalRecordColumns(entity);
  return `export type ${E}Record = {
${recordCols.map((c) => `  ${c.graphqlName}: ${tsTypeForColumn(c)}${c.notNull ? "" : " | null"};`).join("\n")}
};`;
}

export function generateEntityRecordsModule(entities: EntityModel[]): string {
  const blocks = entities.map((e) => recordTypeDefinition(e)).join("\n\n");
  return `// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
${blocks}
`;
}
