import type { EntityModel } from "../model.js";

/** graphql-codegen `mappers` entries (paths relative to `src/generated/graphql/resolvers.generated.ts`). */
export function generateGraphqlCodegenMappersModule(entities: EntityModel[]): string {
  const entries = entities
    .map(
      (e) =>
        `  ${e.graphqlType}: "../dal/repositories/generated-${e.fieldBasename}.repository.js#${e.graphqlType}Record",`,
    )
    .join("\n");

  return `// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
/** Passed to graphql-codegen typescript-resolvers \`mappers\`. */
export const graphqlCodegenMappers = {
${entries}
} as const satisfies Record<string, string>;
`;
}
