import type { EntityModel } from "../model.js";

function sortedEntities(entities: EntityModel[]): EntityModel[] {
  return [...entities].sort((a, b) => a.fieldBasename.localeCompare(b.fieldBasename));
}

/** Emits type-safe pub/sub topic map and factory instance for all entities + bootstrap topics. */
export function generatePubSub(entities: EntityModel[]): string {
  const entityTopics = sortedEntities(entities)
    .map((entity) => {
      const topic = `${entity.fieldBasename.toUpperCase()}_CHANGED`;
      return `  ${topic}: [{ ${entity.fieldBasename}Changed: EntityChangeEventPayload }];`;
    })
    .join("\n");

  return `// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { createAppPubSub } from "@corpdk/pub-sub";
import type { EntityChangeEventPayload } from "@corpdk/dal-core";

/** Type-safe pub/sub topics for bootstrap and DAL entity change events. */
export type PubSubTopics = {
  PING_SENT: [{ pingSent: { message: string; timestamp: string } }];
${entityTopics}
};

export const pubsub = createAppPubSub<PubSubTopics>();
export type PubSub = typeof pubsub;
`;
}
