import type { ColumnModel, EntityModel } from "../model.js";

function pascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function tsTypeForColumn(col: ColumnModel): string {
  if (col.kind === "boolean") return "boolean";
  if (col.kind === "enum" && col.enumValues?.length) {
    return col.enumValues.map((value) => JSON.stringify(value)).join(" | ");
  }
  return "string";
}

function assignCreateValue(col: ColumnModel): string {
  if (col.kind === "timestamptz") {
    return `      ${col.drizzleKey}: input.${col.graphqlName} ? parseDateTime(input.${col.graphqlName}) : undefined,`;
  }
  if (col.kind === "enum") {
    return `      ${col.drizzleKey}: input.${col.graphqlName} as (typeof table.$inferInsert)["${col.drizzleKey}"],`;
  }
  return `      ${col.drizzleKey}: input.${col.graphqlName},`;
}

function assignUpdateValue(col: ColumnModel): string {
  if (col.kind === "timestamptz") {
    if (col.notNull) {
      return `    if (input.${col.graphqlName} !== undefined && input.${col.graphqlName} !== null) {
      set.${col.drizzleKey} = parseDateTime(input.${col.graphqlName});
    }`;
    }
    return `    if (input.${col.graphqlName} !== undefined) {
      set.${col.drizzleKey} = input.${col.graphqlName} === null ? null : parseDateTime(input.${col.graphqlName});
    }`;
  }
  if (col.kind === "enum") {
    return `    if (input.${col.graphqlName} !== undefined) {
      set.${col.drizzleKey} = input.${col.graphqlName} as (typeof table.$inferInsert)["${col.drizzleKey}"];
    }`;
  }
  return `    if (input.${col.graphqlName} !== undefined) {
      set.${col.drizzleKey} = input.${col.graphqlName};
    }`;
}

export function generateRepository(entity: EntityModel): string {
  const E = entity.graphqlType;
  const e = entity.fieldBasename;
  const exportName = entity.exportName;
  const soft = entity.deleteStrategy === "soft";
  const full = entity.auditProfile === "full";

  const businessCols = entity.columns.filter((c) => c.isBusiness);
  const outputCols = entity.columns.filter(
    (c) => c.drizzleKey !== "deletedAt" && c.drizzleKey !== "deletedBy",
  );

  const mapRowFields = outputCols
    .map((col) => {
      if (col.kind === "timestamptz") {
        return col.notNull
          ? `    ${col.graphqlName}: serializeDateTime(row.${col.drizzleKey})!,`
          : `    ${col.graphqlName}: row.${col.drizzleKey} != null ? serializeDateTime(row.${col.drizzleKey}) : null,`;
      }
      return `    ${col.graphqlName}: row.${col.drizzleKey},`;
    })
    .join("\n");

  const filterCases = entity.columns
    .filter((c) => !c.isServerManaged || c.drizzleKey === "id")
    .map((col) => {
      const builder =
        col.kind === "boolean"
          ? "buildBooleanFilter"
          : col.kind === "timestamptz"
            ? "buildDateTimeFilter"
            : col.kind === "uuid"
              ? "buildIdFilter"
              : "buildStringFilter";
      return `    if (node.${col.graphqlName} !== undefined) {
      const part = ${builder}(table.${col.drizzleKey}, node.${col.graphqlName});
      if (part) leafParts.push(part);
    }`;
    })
    .join("\n");

  const createValues = businessCols.map((col) => assignCreateValue(col)).join("\n");

  const updateSet = full ? businessCols.map((col) => assignUpdateValue(col)).join("\n") : "";

  return `// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { and, asc, count, desc, eq, gt, lt, sql, type SQL } from "drizzle-orm";
import {
  assertValidUuid,
  buildBooleanFilter,
  buildDateTimeFilter,
  buildIdFilter,
  buildStringFilter,
  combineLogical,
  createUserError,
  DEFAULT_LIST_LIMIT,
  errorPayload,
  mapDriverError,
  MAX_LIST_LIMIT,
  NotFoundError,
  parseDateTime,
  resolveActorId,
  serializeDateTime,
  successPayload,
  ValidationError,
  type EntityChangeEventPayload,
  type RepositoryContext,
  type SortInput,
} from "@corpdk/dal-core";
import { db } from "../../../db/index.js";
import { ${exportName} } from "../../../db/schema/index.js";

const table = ${exportName};

export type ${E}Record = {
${outputCols.map((c) => `  ${c.graphqlName}: ${tsTypeForColumn(c)}${c.notNull ? "" : " | null"};`).join("\n")}
};

export type ${E}CreateInput = {
${businessCols.map((c) => `  ${c.graphqlName}${c.notNull && !c.hasDefault ? "" : "?"}: ${tsTypeForColumn(c)}${!c.notNull ? " | null" : ""};`).join("\n")}
};

${full ? `export type ${E}UpdateInput = Partial<${E}CreateInput>;` : ""}

export type ${E}Filter = Record<string, unknown> & {
  and?: ${E}Filter[];
  or?: ${E}Filter[];
  not?: ${E}Filter;
};

function mapRow(row: typeof table.$inferSelect): ${E}Record {
  return {
${mapRowFields}
  };
}

function buildWhere(filter: ${E}Filter | null | undefined, includeDeleted?: boolean | null): SQL | undefined {
  const parts: SQL[] = [];
  ${soft ? `if (!includeDeleted) {
    parts.push(sql\`\${table.deletedAt} IS NULL\`);
  }` : ""}

  const leaf = (node: ${E}Filter): SQL | undefined => {
    const leafParts: SQL[] = [];
${filterCases}
    if (leafParts.length === 0) return undefined;
    return leafParts.length === 1 ? leafParts[0] : and(...leafParts)!;
  };

  const logical = combineLogical(filter, leaf);
  if (logical) parts.push(logical);
  if (parts.length === 0) return undefined;
  return parts.length === 1 ? parts[0] : and(...parts)!;
}

const SORT_FIELD_MAP: Record<string, keyof typeof table.$inferSelect> = {
${entity.columns
  .filter((c) => c.drizzleKey !== "deletedAt" && c.drizzleKey !== "deletedBy")
  .map(
    (c) =>
      `  ${c.graphqlName.replace(/([A-Z])/g, "_$1").toUpperCase()}: "${c.drizzleKey}",`,
  )
  .join("\n")}
};

function buildOrder(sort?: SortInput[] | null): SQL[] {
  if (!sort?.length) return [asc(table.id)];
  return sort.map((s) => {
    const dir = s.direction === "DESC" ? desc : asc;
    const drizzleKey = SORT_FIELD_MAP[s.field];
    if (!drizzleKey) throw new ValidationError(\`Invalid sort field: \${s.field}\`, ["sort"]);
    const col = table[drizzleKey as keyof typeof table];
    return dir(col as typeof table.id);
  });
}

function clampLimit(limit?: number | null): number {
  const n = limit ?? DEFAULT_LIST_LIMIT;
  if (n > MAX_LIST_LIMIT) throw new ValidationError(\`limit must be <= \${MAX_LIST_LIMIT}\`, ["limit"]);
  return n;
}

export class Generated${E}Repository {
  mapRow = mapRow;

  async findById(id: string, opts?: { includeDeleted?: boolean | null }): Promise<${E}Record | null> {
    assertValidUuid(id);
    const where = buildWhere({ id: { eq: id } } as ${E}Filter, opts?.includeDeleted);
    const rows = await db.select().from(table).where(where!);
    if (rows.length === 0) return null;
    return mapRow(rows[0]);
  }

  async list(args: {
    filter?: ${E}Filter | null;
    sort?: SortInput[] | null;
    limit?: number | null;
    includeDeleted?: boolean | null;
  }): Promise<${E}Record[]> {
    const where = buildWhere(args.filter, args.includeDeleted);
    const limit = clampLimit(args.limit);
    let q = db.select().from(table).orderBy(...buildOrder(args.sort)).limit(limit);
    if (where) q = q.where(where) as typeof q;
    const rows = await q;
    return rows.map(mapRow);
  }

  async count(args: {
    filter?: ${E}Filter | null;
    includeDeleted?: boolean | null;
  }): Promise<number> {
    const where = buildWhere(args.filter, args.includeDeleted);
    let q = db.select({ value: count() }).from(table);
    if (where) q = q.where(where) as typeof q;
    const rows = await q;
    return Number(rows[0]?.value ?? 0);
  }

  async listConnection(args: {
    filter?: ${E}Filter | null;
    sort?: SortInput[] | null;
    first?: number | null;
    after?: string | null;
    includeDeleted?: boolean | null;
  }) {
    const first = clampLimit(args.first ?? DEFAULT_LIST_LIMIT);
    const whereParts: SQL[] = [];
    const baseWhere = buildWhere(args.filter, args.includeDeleted);
    if (baseWhere) whereParts.push(baseWhere);
    if (args.after) {
      assertValidUuid(args.after, "after");
      whereParts.push(gt(table.id, args.after));
    }
    const where = whereParts.length ? and(...whereParts) : undefined;
    let q = db.select().from(table).orderBy(asc(table.id)).limit(first + 1);
    if (where) q = q.where(where) as typeof q;
    const rows = await q;
    const hasNextPage = rows.length > first;
    const slice = hasNextPage ? rows.slice(0, first) : rows;
    const nodes = slice.map(mapRow);
    const edges = nodes.map((node) => ({ node, cursor: node.id }));
    return {
      edges,
      nodes,
      pageInfo: {
        hasNextPage,
        hasPreviousPage: Boolean(args.after),
        startCursor: edges[0]?.cursor ?? null,
        endCursor: edges[edges.length - 1]?.cursor ?? null,
      },
    };
  }

  async create(input: ${E}CreateInput, ctx: RepositoryContext) {
    try {
      const actor = resolveActorId(ctx.actorId);
      const now = new Date();
      const values = {
${createValues}
        createdAt: now,
        ${full ? "updatedAt: now," : ""}
        createdBy: actor,
        ${full ? "updatedBy: actor," : ""}
      };
      const inserted = await db.insert(table).values(values).returning();
      const row = mapRow(inserted[0]);
      return successPayload({ ${e}: row });
    } catch (err) {
      if (err instanceof ValidationError) {
        return errorPayload({ ${e}: null }, [createUserError("VALIDATION_FAILED", err.message, { field: err.field })]);
      }
      return errorPayload({ ${e}: null }, [mapDriverError(err)]);
    }
  }

  ${full ? `async update(id: string, input: ${E}UpdateInput, ctx: RepositoryContext) {
    try {
      assertValidUuid(id);
      const existing = await this.findById(id);
      if (!existing) {
        return errorPayload({ ${e}: null }, [createUserError("NOT_FOUND", "${E} not found", { id })]);
      }
      const actor = resolveActorId(ctx.actorId);
      const set: Partial<typeof table.$inferInsert> = {
        updatedAt: new Date(),
        updatedBy: actor,
      };
${updateSet}
      const updated = await db.update(table).set(set).where(eq(table.id, id)).returning();
      return successPayload({ ${e}: mapRow(updated[0]) });
    } catch (err) {
      if (err instanceof ValidationError) {
        return errorPayload({ ${e}: null }, [createUserError("VALIDATION_FAILED", err.message, { field: err.field })]);
      }
      return errorPayload({ ${e}: null }, [mapDriverError(err)]);
    }
  }` : ""}

  async delete(id: string, ctx: RepositoryContext) {
    try {
      assertValidUuid(id);
      const existing = await this.findById(id);
      if (!existing) {
        return errorPayload({ success: false }, [createUserError("NOT_FOUND", "${E} not found", { id })]);
      }
      ${soft ? `const actor = resolveActorId(ctx.actorId);
      await db.update(table).set({ deletedAt: new Date(), deletedBy: actor }).where(eq(table.id, id));` : `await db.delete(table).where(eq(table.id, id));`}
      return successPayload({ success: true });
    } catch (err) {
      return errorPayload({ success: false }, [mapDriverError(err)]);
    }
  }

  toChangeEvent(operation: EntityChangeEventPayload["operation"], ids: string[]): EntityChangeEventPayload {
    const count = ids.length;
    const isTruncated = count > 100;
    return {
      operation,
      ids: isTruncated ? [] : ids,
      isTruncated,
      count,
    };
  }
}
`;
}

export function generateRepositoryIndex(entities: EntityModel[]): string {
  const imports = entities
    .map(
      (e) =>
        `export { Generated${e.graphqlType}Repository } from "./generated-${e.fieldBasename}.repository.js";`,
    )
    .join("\n");
  return `// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
${imports}
`;
}
