import type { EntityModel } from "../model.js";

export function generateResolvers(entities: EntityModel[]): string {
  const queryFields: string[] = [];
  const mutationFields: string[] = [];
  const subscriptionFields: string[] = [];

  for (const entity of entities) {
    const E = entity.graphqlType;
    const e = entity.fieldBasename;
    const list = entity.listField;
    const full = entity.auditProfile === "full";
    const topic = `${e.toUpperCase()}_CHANGED`;

    queryFields.push(`    ${list}: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.${e}.list({
        filter: args.filter as never,
        sort: args.sort as never,
        limit: args.limit as number | null,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    ${e}: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.${e}.findById(args.id, { includeDeleted: args.includeDeleted }),

    ${e}Connection: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.${e}.listConnection({
        filter: args.filter as never,
        sort: args.sort as never,
        first: args.first as number | null,
        after: args.after as string | null,
        last: args.last as number | null,
        before: args.before as string | null,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    ${list}Count: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.${e}.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    ${e}Aggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.${e}.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),`);

    mutationFields.push(`    create${E}: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.${e}.create(args.input as never, { actorId: ctx.actorId });
      if (result.${e} && result.userErrors.length === 0) {
        const event = ctx.repositories.${e}.toChangeEvent("CREATED", [result.${e}.id]);
        ctx.pubsub.publish("${topic}", { ${e}Changed: event });
      }
      return result;
    },`);

    if (full) {
      mutationFields.push(`    update${E}: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.${e}.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.${e} && result.userErrors.length === 0) {
        const event = ctx.repositories.${e}.toChangeEvent("UPDATED", [result.${e}.id]);
        ctx.pubsub.publish("${topic}", { ${e}Changed: event });
      }
      return result;
    },`);
    }

    mutationFields.push(`    delete${E}: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.${e}.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.${e}.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("${topic}", { ${e}Changed: event });
      }
      return result;
    },`);

    subscriptionFields.push(`    ${e}Changed: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("${topic}")) {
          const event = payload.${e}Changed;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },`);
  }

  const repoImports =
    entities.length === 0
      ? ""
      : `import {\n${entities.map((e) => `  Generated${e.graphqlType}Repository,`).join("\n")}\n} from "../repositories/index.js";`;

  const repoTypeFields = entities
    .map((e) => `    ${e.fieldBasename}: Generated${e.graphqlType}Repository;`)
    .join("\n");

  const repoInitFields = entities
    .map((e) => `    ${e.fieldBasename}: new Generated${e.graphqlType}Repository(),`)
    .join("\n");

  const scalarBlock = `  DateTime: {
    serialize: (v: unknown) => (v instanceof Date ? v.toISOString() : v),
    parseValue: (v: unknown) => {
      if (typeof v !== "string") throw new TypeError("DateTime must be a string");
      return v;
    },
    parseLiteral: (ast: { kind: string; value?: string }) => {
      if (ast.kind !== Kind.STRING) throw new TypeError("DateTime must be a string");
      return ast.value ?? "";
    },
  },`;

  return `// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { Kind } from "graphql";
import type { PubSub } from "../generated-pubsub.js";
${repoImports}

export interface DalContext {
  actorId: string | null;
  pubsub: PubSub;
  repositories: {
${repoTypeFields}
  };
}

export interface CreateDalContextOptions {
  /** Actor ID from auth context; null uses repository "system" fallback. */
  actorId?: string | null;
}

export function createDalContext(pubsub: PubSub, options?: CreateDalContextOptions): DalContext {
  return {
    actorId: options?.actorId ?? null,
    pubsub,
    repositories: {
${repoInitFields}
    },
  };
}

export const generatedResolvers = {
${scalarBlock}
  Query: {
    hello: (_: unknown, args: { name?: string | null }): string =>
      \`Hello, \${args.name ?? "world"}!\`,

    status: (): { ok: boolean; timestamp: string } => ({
      ok: true,
      timestamp: new Date().toISOString(),
    }),

${queryFields.join("\n\n")}
  },
  Mutation: {
    ping: (
      _: unknown,
      args: { message: string },
      ctx: DalContext,
    ): { message: string; timestamp: string } => {
      const result = { message: args.message, timestamp: new Date().toISOString() };
      ctx.pubsub.publish("PING_SENT", { pingSent: result });
      return result;
    },

${mutationFields.join("\n\n")}
  },
  Subscription: {
    pingSent: {
      subscribe: (_: unknown, _args: unknown, ctx: DalContext) =>
        ctx.pubsub.subscribe("PING_SENT"),
    },

${subscriptionFields.join("\n\n")}
  },
};
`;
}
