import { lexicographicSortSchema, printSchema } from "graphql";
import type { EntityModel } from "../model.js";
import { buildDalGraphQLSchema } from "./schema-builder.js";

/** Builds merged GraphQL SDL from entity models via programmatic schema construction. */
export function generateMergedTypeDefs(entities: EntityModel[]): string {
  const schema = buildDalGraphQLSchema(entities);
  return printSchema(lexicographicSortSchema(schema));
}

const SCHEMA_MODULE_BANNER = "// AUTO-GENERATED by @corpdk/dal-codegen — do not edit\n";

/** Escapes SDL for embedding in a TypeScript template literal (`typeDefs`). */
export function escapeSdlForTemplateLiteral(sdl: string): string {
  return sdl
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

/** Emits a committed TypeScript module exporting merged GraphQL SDL as `typeDefs`. */
export function generateSchemaModule(entities: EntityModel[]): string {
  const sdl = generateMergedTypeDefs(entities);
  const escaped = escapeSdlForTemplateLiteral(sdl);
  return `${SCHEMA_MODULE_BANNER}/** Merged GraphQL SDL for all generated entities. */
export const typeDefs = \`${escaped}\`;
`;
}
