import { lexicographicSortSchema, printSchema } from "graphql";
import type { EntityModel } from "../model.js";
import { buildDalGraphQLSchema } from "./schema-builder.js";

/** Builds merged GraphQL SDL from entity models via programmatic schema construction. */
export function generateMergedTypeDefs(entities: EntityModel[]): string {
  const schema = buildDalGraphQLSchema(entities);
  return printSchema(lexicographicSortSchema(schema));
}

const SCHEMA_MODULE_BANNER = "// AUTO-GENERATED by @corpdk/dal-codegen — do not edit\n";

/** Emits a committed TypeScript module exporting merged GraphQL SDL as `typeDefs`. */
export function generateSchemaModule(entities: EntityModel[]): string {
  const sdl = generateMergedTypeDefs(entities);
  return `${SCHEMA_MODULE_BANNER}/** Merged GraphQL SDL for all generated entities. */
export const typeDefs = ${JSON.stringify(sdl)};
`;
}
