// AUTO-GENERATED by @corpdk/dal-codegen — do not edit
import { Kind, type GraphQLResolveInfo } from "graphql";
import { DataLoader } from "@corpdk/dal-core";
import type { PubSub } from "../generated-pubsub.js";
import {
  GeneratedAuditEventRepository,
  GeneratedCategoryRepository,
  GeneratedItemDetailRepository,
  GeneratedItemRepository,
  GeneratedItemTagRepository,
  GeneratedOrderLineRepository,
  GeneratedOrderRepository,
  GeneratedTagRepository,
} from "../repositories/index.js";

export interface DalContext {
  actorId: string | null;
  pubsub: PubSub;
  repositories: {
    auditEvent: GeneratedAuditEventRepository;
    category: GeneratedCategoryRepository;
    itemDetail: GeneratedItemDetailRepository;
    item: GeneratedItemRepository;
    itemTag: GeneratedItemTagRepository;
    orderLine: GeneratedOrderLineRepository;
    order: GeneratedOrderRepository;
    tag: GeneratedTagRepository;
  };
  loaders: Record<string, DataLoader<string, unknown> | DataLoader<string, unknown[]>>;
}

export interface CreateDalContextOptions {
  /** Actor ID from auth context; null uses repository "system" fallback. */
  actorId?: string | null;
}

export function createDalContext(pubsub: PubSub, options?: CreateDalContextOptions): DalContext {
  const repositories = {
    auditEvent: new GeneratedAuditEventRepository(),
    category: new GeneratedCategoryRepository(),
    itemDetail: new GeneratedItemDetailRepository(),
    item: new GeneratedItemRepository(),
    itemTag: new GeneratedItemTagRepository(),
    orderLine: new GeneratedOrderLineRepository(),
    order: new GeneratedOrderRepository(),
    tag: new GeneratedTagRepository(),
  };
  const ctxRef = {
    actorId: options?.actorId ?? null,
    pubsub,
    repositories,
    loaders: {} as DalContext["loaders"],
  } as DalContext;

  ctxRef.loaders.category_items = new DataLoader<string, unknown[]>(async (parentIds) => {
    const grouped = await ctxRef.repositories.item.findByCategoryIds([...parentIds]);
    const map = new Map<string, unknown[]>();
    for (const pid of parentIds) map.set(pid, grouped.get(pid) ?? []);
    return map;
  });

  ctxRef.loaders.itemDetail_item = new DataLoader<string, unknown>(async (ids) => {
    const rows = await ctxRef.repositories.item.findByIds([...ids]);
    const map = new Map<string, unknown>();
    for (const row of rows) map.set(row.id as string, row);
    return map;
  });

  ctxRef.loaders.item_category = new DataLoader<string, unknown>(async (ids) => {
    const rows = await ctxRef.repositories.category.findByIds([...ids]);
    const map = new Map<string, unknown>();
    for (const row of rows) map.set(row.id as string, row);
    return map;
  });

  ctxRef.loaders.item_detail = new DataLoader<string, unknown>(async (parentIds) => {
    const grouped = await ctxRef.repositories.itemDetail.findOneByItemIds([...parentIds]);
    const map = new Map<string, unknown>();
    for (const pid of parentIds) map.set(pid, grouped.get(pid) ?? null);
    return map;
  });

  ctxRef.loaders.item_itemTags = new DataLoader<string, unknown[]>(async (parentIds) => {
    const grouped = await ctxRef.repositories.itemTag.findByItemIds([...parentIds]);
    const map = new Map<string, unknown[]>();
    for (const pid of parentIds) map.set(pid, grouped.get(pid) ?? []);
    return map;
  });

  ctxRef.loaders.itemTag_item = new DataLoader<string, unknown>(async (ids) => {
    const rows = await ctxRef.repositories.item.findByIds([...ids]);
    const map = new Map<string, unknown>();
    for (const row of rows) map.set(row.id as string, row);
    return map;
  });

  ctxRef.loaders.itemTag_tag = new DataLoader<string, unknown>(async (ids) => {
    const rows = await ctxRef.repositories.tag.findByIds([...ids]);
    const map = new Map<string, unknown>();
    for (const row of rows) map.set(row.id as string, row);
    return map;
  });

  ctxRef.loaders.orderLine_order = new DataLoader<string, unknown>(async (ids) => {
    const rows = await ctxRef.repositories.order.findByIds([...ids]);
    const map = new Map<string, unknown>();
    for (const row of rows) map.set(row.id as string, row);
    return map;
  });

  ctxRef.loaders.order_lines = new DataLoader<string, unknown[]>(async (parentIds) => {
    const grouped = await ctxRef.repositories.orderLine.findByOrderIds([...parentIds]);
    const map = new Map<string, unknown[]>();
    for (const pid of parentIds) map.set(pid, grouped.get(pid) ?? []);
    return map;
  });

  ctxRef.loaders.tag_itemTags = new DataLoader<string, unknown[]>(async (parentIds) => {
    const grouped = await ctxRef.repositories.itemTag.findByTagIds([...parentIds]);
    const map = new Map<string, unknown[]>();
    for (const pid of parentIds) map.set(pid, grouped.get(pid) ?? []);
    return map;
  });

  return ctxRef;
}

export const generatedResolvers = {
  DateTime: {
    serialize: (v: unknown) => (v instanceof Date ? v.toISOString() : v),
    parseValue: (v: unknown) => {
      if (typeof v !== "string") throw new TypeError("DateTime must be a string");
      return v;
    },
    parseLiteral: (ast: { kind: string; value?: string }) => {
      if (ast.kind !== Kind.STRING) throw new TypeError("DateTime must be a string");
      return ast.value ?? "";
    },
  },
  Query: {
    hello: (_: unknown, args: { name?: string | null }): string =>
      `Hello, ${args.name ?? "world"}!`,

    status: (): { ok: boolean; timestamp: string } => ({
      ok: true,
      timestamp: new Date().toISOString(),
    }),

    auditEvents: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.auditEvent.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    auditEvent: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.auditEvent.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    auditEventConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.auditEvent.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    auditEventsCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.auditEvent.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    auditEventAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.auditEvent.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    categories: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.category.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    category: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.category.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    categoryConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.category.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    categoriesCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.category.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    categoryAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.category.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    itemDetails: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.itemDetail.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    itemDetail: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.itemDetail.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    itemDetailConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.itemDetail.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    itemDetailsCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.itemDetail.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    itemDetailAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.itemDetail.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    items: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.item.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    item: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.item.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    itemConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.item.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    itemsCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.item.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    itemAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.item.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    itemTags: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.itemTag.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    itemTag: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.itemTag.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    itemTagConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.itemTag.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    itemTagsCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.itemTag.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    itemTagAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.itemTag.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    orderLines: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.orderLine.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    orderLine: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.orderLine.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    orderLineConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.orderLine.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    orderLinesCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.orderLine.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    orderLineAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.orderLine.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    orders: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.order.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    order: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.order.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    orderConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.order.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    ordersCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.order.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    orderAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.order.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),

    tags: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.tag.list(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          limit: args.limit as number | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    tag: (_: unknown, args: { id: string; includeDeleted?: boolean | null }, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.tag.findById(args.id, { includeDeleted: args.includeDeleted }, info),

    tagConnection: (_: unknown, args: Record<string, unknown>, ctx: DalContext, info: GraphQLResolveInfo) =>
      ctx.repositories.tag.listConnection(
        {
          filter: args.filter as never,
          sort: args.sort as never,
          first: args.first as number | null,
          after: args.after as string | null,
          last: args.last as number | null,
          before: args.before as string | null,
          includeDeleted: args.includeDeleted as boolean | null,
        },
        info,
      ),

    tagsCount: (_: unknown, args: Record<string, unknown>, ctx: DalContext) =>
      ctx.repositories.tag.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),

    tagAggregate: async (_: unknown, args: Record<string, unknown>, ctx: DalContext) => ({
      count: await ctx.repositories.tag.count({
        filter: args.filter as never,
        includeDeleted: args.includeDeleted as boolean | null,
      }),
    }),
  },
  Mutation: {
    ping: (
      _: unknown,
      args: { message: string },
      ctx: DalContext,
    ): { message: string; timestamp: string } => {
      const result = { message: args.message, timestamp: new Date().toISOString() };
      ctx.pubsub.publish("PING_SENT", { pingSent: result });
      return result;
    },

    createAuditEvent: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.auditEvent.create(args.input as never, { actorId: ctx.actorId });
      if (result.auditEvent && result.userErrors.length === 0) {
        const event = ctx.repositories.auditEvent.toChangeEvent("CREATED", [result.auditEvent.id]);
        ctx.pubsub.publish("AUDITEVENT_CHANGED", { auditEventChanged: event });
      }
      return result;
    },

    bulkCreateAuditEvent: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.auditEvent.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.auditEvent.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("AUDITEVENT_CHANGED", { auditEventChanged: event });
      }
      return result;
    },

    bulkDeleteAuditEvent: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.auditEvent.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.auditEvent.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("AUDITEVENT_CHANGED", { auditEventChanged: event });
      }
      return result;
    },

    bulkDeleteAuditEventByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.auditEvent.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    deleteAuditEvent: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.auditEvent.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.auditEvent.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("AUDITEVENT_CHANGED", { auditEventChanged: event });
      }
      return result;
    },

    createCategory: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.category.create(args.input as never, { actorId: ctx.actorId });
      if (result.category && result.userErrors.length === 0) {
        const event = ctx.repositories.category.toChangeEvent("CREATED", [result.category.id]);
        ctx.pubsub.publish("CATEGORY_CHANGED", { categoryChanged: event });
      }
      return result;
    },

    bulkCreateCategory: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.category.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.category.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("CATEGORY_CHANGED", { categoryChanged: event });
      }
      return result;
    },

    bulkDeleteCategory: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.category.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.category.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("CATEGORY_CHANGED", { categoryChanged: event });
      }
      return result;
    },

    bulkDeleteCategoryByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.category.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updateCategory: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.category.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.category && result.userErrors.length === 0) {
        const event = ctx.repositories.category.toChangeEvent("UPDATED", [result.category.id]);
        ctx.pubsub.publish("CATEGORY_CHANGED", { categoryChanged: event });
      }
      return result;
    },

    bulkUpdateCategory: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.category.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.category.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("CATEGORY_CHANGED", { categoryChanged: event });
      }
      return result;
    },

    bulkUpdateCategoryByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.category.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deleteCategory: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.category.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.category.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("CATEGORY_CHANGED", { categoryChanged: event });
      }
      return result;
    },

    createItemDetail: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.itemDetail.create(args.input as never, { actorId: ctx.actorId });
      if (result.itemDetail && result.userErrors.length === 0) {
        const event = ctx.repositories.itemDetail.toChangeEvent("CREATED", [result.itemDetail.id]);
        ctx.pubsub.publish("ITEMDETAIL_CHANGED", { itemDetailChanged: event });
      }
      return result;
    },

    bulkCreateItemDetail: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.itemDetail.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.itemDetail.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ITEMDETAIL_CHANGED", { itemDetailChanged: event });
      }
      return result;
    },

    bulkDeleteItemDetail: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.itemDetail.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.itemDetail.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("ITEMDETAIL_CHANGED", { itemDetailChanged: event });
      }
      return result;
    },

    bulkDeleteItemDetailByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.itemDetail.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updateItemDetail: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.itemDetail.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.itemDetail && result.userErrors.length === 0) {
        const event = ctx.repositories.itemDetail.toChangeEvent("UPDATED", [result.itemDetail.id]);
        ctx.pubsub.publish("ITEMDETAIL_CHANGED", { itemDetailChanged: event });
      }
      return result;
    },

    bulkUpdateItemDetail: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.itemDetail.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.itemDetail.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ITEMDETAIL_CHANGED", { itemDetailChanged: event });
      }
      return result;
    },

    bulkUpdateItemDetailByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.itemDetail.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deleteItemDetail: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.itemDetail.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.itemDetail.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("ITEMDETAIL_CHANGED", { itemDetailChanged: event });
      }
      return result;
    },

    createItem: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.item.create(args.input as never, { actorId: ctx.actorId });
      if (result.item && result.userErrors.length === 0) {
        const event = ctx.repositories.item.toChangeEvent("CREATED", [result.item.id]);
        ctx.pubsub.publish("ITEM_CHANGED", { itemChanged: event });
      }
      return result;
    },

    bulkCreateItem: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.item.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.item.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ITEM_CHANGED", { itemChanged: event });
      }
      return result;
    },

    bulkDeleteItem: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.item.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.item.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("ITEM_CHANGED", { itemChanged: event });
      }
      return result;
    },

    bulkDeleteItemByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.item.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updateItem: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.item.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.item && result.userErrors.length === 0) {
        const event = ctx.repositories.item.toChangeEvent("UPDATED", [result.item.id]);
        ctx.pubsub.publish("ITEM_CHANGED", { itemChanged: event });
      }
      return result;
    },

    bulkUpdateItem: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.item.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.item.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ITEM_CHANGED", { itemChanged: event });
      }
      return result;
    },

    bulkUpdateItemByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.item.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deleteItem: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.item.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.item.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("ITEM_CHANGED", { itemChanged: event });
      }
      return result;
    },

    createItemTag: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.itemTag.create(args.input as never, { actorId: ctx.actorId });
      if (result.itemTag && result.userErrors.length === 0) {
        const event = ctx.repositories.itemTag.toChangeEvent("CREATED", [result.itemTag.id]);
        ctx.pubsub.publish("ITEMTAG_CHANGED", { itemTagChanged: event });
      }
      return result;
    },

    bulkCreateItemTag: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.itemTag.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.itemTag.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ITEMTAG_CHANGED", { itemTagChanged: event });
      }
      return result;
    },

    bulkDeleteItemTag: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.itemTag.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.itemTag.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("ITEMTAG_CHANGED", { itemTagChanged: event });
      }
      return result;
    },

    bulkDeleteItemTagByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.itemTag.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updateItemTag: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.itemTag.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.itemTag && result.userErrors.length === 0) {
        const event = ctx.repositories.itemTag.toChangeEvent("UPDATED", [result.itemTag.id]);
        ctx.pubsub.publish("ITEMTAG_CHANGED", { itemTagChanged: event });
      }
      return result;
    },

    bulkUpdateItemTag: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.itemTag.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.itemTag.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ITEMTAG_CHANGED", { itemTagChanged: event });
      }
      return result;
    },

    bulkUpdateItemTagByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.itemTag.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deleteItemTag: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.itemTag.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.itemTag.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("ITEMTAG_CHANGED", { itemTagChanged: event });
      }
      return result;
    },

    createOrderLine: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.orderLine.create(args.input as never, { actorId: ctx.actorId });
      if (result.orderLine && result.userErrors.length === 0) {
        const event = ctx.repositories.orderLine.toChangeEvent("CREATED", [result.orderLine.id]);
        ctx.pubsub.publish("ORDERLINE_CHANGED", { orderLineChanged: event });
      }
      return result;
    },

    bulkCreateOrderLine: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.orderLine.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.orderLine.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ORDERLINE_CHANGED", { orderLineChanged: event });
      }
      return result;
    },

    bulkDeleteOrderLine: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.orderLine.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.orderLine.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("ORDERLINE_CHANGED", { orderLineChanged: event });
      }
      return result;
    },

    bulkDeleteOrderLineByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.orderLine.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updateOrderLine: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.orderLine.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.orderLine && result.userErrors.length === 0) {
        const event = ctx.repositories.orderLine.toChangeEvent("UPDATED", [result.orderLine.id]);
        ctx.pubsub.publish("ORDERLINE_CHANGED", { orderLineChanged: event });
      }
      return result;
    },

    bulkUpdateOrderLine: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.orderLine.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.orderLine.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ORDERLINE_CHANGED", { orderLineChanged: event });
      }
      return result;
    },

    bulkUpdateOrderLineByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.orderLine.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deleteOrderLine: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.orderLine.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.orderLine.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("ORDERLINE_CHANGED", { orderLineChanged: event });
      }
      return result;
    },

    createOrder: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.order.create(args.input as never, { actorId: ctx.actorId });
      if (result.order && result.userErrors.length === 0) {
        const event = ctx.repositories.order.toChangeEvent("CREATED", [result.order.id]);
        ctx.pubsub.publish("ORDER_CHANGED", { orderChanged: event });
      }
      return result;
    },

    bulkCreateOrder: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.order.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.order.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ORDER_CHANGED", { orderChanged: event });
      }
      return result;
    },

    bulkDeleteOrder: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.order.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.order.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("ORDER_CHANGED", { orderChanged: event });
      }
      return result;
    },

    bulkDeleteOrderByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.order.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    updateOrder: async (_: unknown, args: { id: string; input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.order.update(args.id, args.input as never, { actorId: ctx.actorId });
      if (result.order && result.userErrors.length === 0) {
        const event = ctx.repositories.order.toChangeEvent("UPDATED", [result.order.id]);
        ctx.pubsub.publish("ORDER_CHANGED", { orderChanged: event });
      }
      return result;
    },

    bulkUpdateOrder: async (_: unknown, args: { updates: Array<{ id: string; input: Record<string, unknown> }>; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.order.bulkUpdate(args.updates as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.order.toChangeEvent("UPDATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("ORDER_CHANGED", { orderChanged: event });
      }
      return result;
    },

    bulkUpdateOrderByFilter: async (_: unknown, args: { filter: Record<string, unknown>; input: Record<string, unknown>; confirmUpdateAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.order.bulkUpdateByFilter(args.filter as never, args.input as never, { actorId: ctx.actorId }, args.confirmUpdateAll),

    deleteOrder: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.order.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.order.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("ORDER_CHANGED", { orderChanged: event });
      }
      return result;
    },

    createTag: async (_: unknown, args: { input: Record<string, unknown> }, ctx: DalContext) => {
      const result = await ctx.repositories.tag.create(args.input as never, { actorId: ctx.actorId });
      if (result.tag && result.userErrors.length === 0) {
        const event = ctx.repositories.tag.toChangeEvent("CREATED", [result.tag.id]);
        ctx.pubsub.publish("TAG_CHANGED", { tagChanged: event });
      }
      return result;
    },

    bulkCreateTag: async (_: unknown, args: { inputs: Record<string, unknown>[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.tag.bulkCreate(args.inputs as never, { actorId: ctx.actorId }, args.atomic);
      if ("items" in result && result.items.length > 0) {
        const event = ctx.repositories.tag.toChangeEvent("CREATED", result.items.map((row) => row.id));
        ctx.pubsub.publish("TAG_CHANGED", { tagChanged: event });
      }
      return result;
    },

    bulkDeleteTag: async (_: unknown, args: { ids: string[]; atomic?: boolean | null }, ctx: DalContext) => {
      const result = await ctx.repositories.tag.bulkDelete(args.ids, { actorId: ctx.actorId }, args.atomic);
      if ("count" in result && result.count > 0) {
        const event = ctx.repositories.tag.toChangeEvent("DELETED", args.ids);
        ctx.pubsub.publish("TAG_CHANGED", { tagChanged: event });
      }
      return result;
    },

    bulkDeleteTagByFilter: async (_: unknown, args: { filter: Record<string, unknown>; confirmDeleteAll?: boolean | null }, ctx: DalContext) =>
      ctx.repositories.tag.bulkDeleteByFilter(args.filter as never, { actorId: ctx.actorId }, args.confirmDeleteAll),

    deleteTag: async (_: unknown, args: { id: string }, ctx: DalContext) => {
      const result = await ctx.repositories.tag.delete(args.id, { actorId: ctx.actorId });
      if (result.success && result.userErrors.length === 0) {
        const event = ctx.repositories.tag.toChangeEvent("DELETED", [args.id]);
        ctx.pubsub.publish("TAG_CHANGED", { tagChanged: event });
      }
      return result;
    },
  },
  Subscription: {
    pingSent: {
      subscribe: (_: unknown, _args: unknown, ctx: DalContext) =>
        ctx.pubsub.subscribe("PING_SENT"),
    },

    auditEventChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("AUDITEVENT_CHANGED")) {
          const event = payload.auditEventChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    categoryChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("CATEGORY_CHANGED")) {
          const event = payload.categoryChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    itemDetailChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("ITEMDETAIL_CHANGED")) {
          const event = payload.itemDetailChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    itemChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("ITEM_CHANGED")) {
          const event = payload.itemChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    itemTagChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("ITEMTAG_CHANGED")) {
          const event = payload.itemTagChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    orderLineChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("ORDERLINE_CHANGED")) {
          const event = payload.orderLineChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    orderChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("ORDER_CHANGED")) {
          const event = payload.orderChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },

    tagChanged: {
      subscribe: async function* (_: unknown, args: { subscribeTo?: string[] | null }, ctx: DalContext) {
        const allowed =
          args.subscribeTo?.length ? new Set(args.subscribeTo) : null;
        for await (const payload of ctx.pubsub.subscribe("TAG_CHANGED")) {
          const event = payload.tagChanged;
          if (allowed === null || allowed.has(event.operation)) {
            yield payload;
          }
        }
      },
    },
  },

  Category: {
    items: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const id = parent.id as string;
      return ctx.loaders.category_items!.load(id);
    },
  },

  ItemDetail: {
    item: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const fk = parent.itemId as string | null | undefined;
      if (fk == null) return null;
      return ctx.loaders.itemDetail_item!.load(fk);
    },
  },

  Item: {
    category: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const fk = parent.categoryId as string | null | undefined;
      if (fk == null) return null;
      return ctx.loaders.item_category!.load(fk);
    },
    detail: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) =>
      ctx.loaders.item_detail!.load(parent.id as string),
    itemTags: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const id = parent.id as string;
      return ctx.loaders.item_itemTags!.load(id);
    },
  },

  ItemTag: {
    item: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const fk = parent.itemId as string | null | undefined;
      if (fk == null) return null;
      return ctx.loaders.itemTag_item!.load(fk);
    },
    tag: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const fk = parent.tagId as string | null | undefined;
      if (fk == null) return null;
      return ctx.loaders.itemTag_tag!.load(fk);
    },
  },

  OrderLine: {
    order: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const fk = parent.orderId as string | null | undefined;
      if (fk == null) return null;
      return ctx.loaders.orderLine_order!.load(fk);
    },
  },

  Order: {
    lines: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const id = parent.id as string;
      return ctx.loaders.order_lines!.load(id);
    },
  },

  Tag: {
    itemTags: (parent: Record<string, unknown>, _: unknown, ctx: DalContext) => {
      const id = parent.id as string;
      return ctx.loaders.tag_itemTags!.load(id);
    },
  },
};
